import { describe, expect, it } from "vitest";
import {
	getGetApiV1ClassesByNameByClassNameObjectsByNameByObjectNameUrl,
	getGetApiV1ClassesByNameByClassNameUrl,
} from "@/lib/api/generated/client";

describe("generated by-name URL builders", () => {
	it("encodes class names as a single path segment", () => {
		expect(getGetApiV1ClassesByNameByClassNameUrl("class / ?#%")).toBe(
			"/_hubuum-bff/hubuum/api/v1/classes/by-name/class%20%2F%20%3F%23%25",
		);
	});

	it("encodes class and object names independently", () => {
		expect(
			getGetApiV1ClassesByNameByClassNameObjectsByNameByObjectNameUrl(
				"class/name",
				"object?#%",
			),
		).toBe(
			"/_hubuum-bff/hubuum/api/v1/classes/by-name/class%2Fname/objects/by-name/object%3F%23%25",
		);
	});
});
